project:
  type: book
  output-dir: docs


book:
  title: "Research Methods and Data Analysis (IAWEL)"
  author: "Jill R D MacKay"
  search: true
  downloads: [pdf, epub]
  date: last-modified
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - week01.qmd
    - week02.qmd
    - week03.qmd
    - week04.qmd
    - week05.qmd
    - week06.qmd
    - week07.qmd
    - week089.qmd
    - week10.qmd
    - refs.qmd


bibliography: references.bib

format:
  html:
    theme: Yeti
    code-copy: true
  pdf:
    documentclass: scrreport
  epub:
    cover-image: "assets/cover.png"
    
