---
title: "Week 4: Considerations for Collecting Data"
format: html
editor: source
execute: 
  eval: FALSE
  echo: TRUE
  warning: FALSE
  message: FALSE
---

```{r, "Week 2 Set Up", eval = TRUE, echo = FALSE}
library(tidyverse)
library(report)




cat_weights <- tibble(avg_daily_snacks  = c(3, 2, 4, 2, 3, 1, 1, 0, 1, 0, 2, 3, 1, 2, 1, 3),
                      weight = c(3.8, 3.9, 5, 3.7,  4.1, 3.6, 3.7, 3.6, 3.8, 4.1, 4.3, 3.9, 3.7, 3.8, 3.5, 4.3))


```



# Lecture: Effect Sizes and Covariance {.unnumbered}


## Mock Data and visualisation {.unnumbered}


```{r}
#| echo: true
#| eval: true


job_dat <- tibble(job = c("vet", "vet", "vet","vet", "vet", "vet", "vet", "vet", "vet", "vet",
                          "assc", "assc", "assc", "assc", "assc", "assc", "assc", "assc", "assc", "assc"),
                  burnout = c(13, 12, 4, 16, 16, 20, 8, 10, 11, 10,
                              10, 11, 8, 7, 8, 10, 9, 11, 17, 10),
                  empathy = c(4, 5, 1, 4,3, 5, 2, 3,3,2,
                              2, 3, 3, 2, 2, 3, 3, 4, 5, 2),
                  satisfaction = c("yes", "no", "no", "no", "yes", "no", "yes", "no", "yes", "yes",
                                   "yes", "yes", "yes", "no", "yes", "yes", "yes","no", "yes", "yes"))


job_dat |> 
  ggplot(aes(x = burnout, y = empathy, shape = job, colour = satisfaction)) +
  geom_point() +
  theme_classic() +
  labs(title = "Burnout and empathy scores for vets and associated professions",
       subtitle = "Job Satisfaction shown",
       caption = "Mock data for teaching",
       x = "Burnout Score",
       y = "Empathy Score") +
  scale_shape_discrete(name = "Vet or Associated Profession") +
  scale_color_discrete(name = "Satisfied with job?") 





```



## Calculcate Cohen's d {.unnumbered}

```{r}
#| eval: TRUE
library(effsize)

cohen.d(d = job_dat$burnout, f = job_dat$job)

```


## Calculcate Hedge's g {.unnumbered}

```{r}
#| eval: TRUE

cohen.d(d = job_dat$burnout, f = job_dat$job, hedges.correction = TRUE)

```


## Effects of Differences {.unnumbered}

```{r}
#| eval: true

job_dat |> 
  ggplot(aes(x = burnout, y = empathy)) +
  geom_point() +
  theme_classic() +
  labs(x = "Burnout Score", y = "Empathy Score")


```

## Correlation coefficient (r) {.unnumbered}

```{r}
#| eval: true

cor(job_dat$burnout, job_dat$empathy, method = "pearson")


```


## Other Correlation Coefficients {.unnumbered}


```{r}
#| eval: true
cor(job_dat$burnout, job_dat$empathy, method = "spearman")

cor.test(job_dat$burnout, as.numeric(as.factor(job_dat$job)))

```


## Cramer's V {.unnumbered}


```{r}
#| eval: true

library(lsr)



job_tbl <- xtabs(~job_dat$burnout +  job_dat$satisfaction)
ftable(job_tbl)
chisq.test(ftable(job_tbl))
cramersV(ftable(job_tbl))



```
